import { Employee, AttendanceLog, LeaveRequest, ReimbursementClaim, PayrollSlip } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-101',
    name: 'Sarah Connor',
    email: 'sarah.connor@skycorp.com',
    phone: '+1 (555) 0192',
    role: 'Senior Software Architect',
    department: 'Engineering',
    status: 'Active',
    joinDate: '2023-03-12',
  },
  {
    id: 'emp-102',
    name: 'James Carter',
    email: 'james.carter@skycorp.com',
    phone: '+1 (555) 0148',
    role: 'Product Designer',
    department: 'Design',
    status: 'Active',
    joinDate: '2024-01-15',
  },
  {
    id: 'emp-103',
    name: 'Elena Rostova',
    email: 'elena.rostova@skycorp.com',
    phone: '+1 (555) 0173',
    role: 'HR Director',
    department: 'HR',
    status: 'Active',
    joinDate: '2022-09-01',
  },
  {
    id: 'emp-104',
    name: 'Marcus Vance',
    email: 'marcus.vance@skycorp.com',
    phone: '+1 (555) 0122',
    role: 'Growth Marketing Lead',
    department: 'Marketing',
    status: 'On Leave',
    joinDate: '2023-11-20',
  },
  {
    id: 'emp-105',
    name: 'David Kim',
    email: 'david.kim@skycorp.com',
    phone: '+1 (555) 0165',
    role: 'Junior Engineer',
    department: 'Engineering',
    status: 'Active',
    joinDate: '2025-02-10',
  },
  {
    id: 'emp-106',
    name: 'Sophia Patel',
    email: 'sophia.patel@skycorp.com',
    phone: '+1 (555) 0119',
    role: 'Account Executive',
    department: 'Sales',
    status: 'Active',
    joinDate: '2024-06-18',
  }
];

export const INITIAL_ATTENDANCE: AttendanceLog[] = [
  {
    id: 'att-1',
    employeeId: 'emp-101',
    employeeName: 'Sarah Connor',
    date: '2026-05-18',
    clockIn: '08:52',
    clockOut: '17:30',
    status: 'Present',
    notes: 'Arrived early to review system migration.',
  },
  {
    id: 'att-2',
    employeeId: 'emp-102',
    employeeName: 'James Carter',
    date: '2026-05-18',
    clockIn: '09:05',
    clockOut: '17:00',
    status: 'Present',
    notes: 'Normal shift.',
  },
  {
    id: 'att-3',
    employeeId: 'emp-103',
    employeeName: 'Elena Rostova',
    date: '2026-05-18',
    clockIn: '08:45',
    clockOut: '18:15',
    status: 'Present',
    notes: 'Conducted three interviews.',
  },
  {
    id: 'att-4',
    employeeId: 'emp-105',
    employeeName: 'David Kim',
    date: '2026-05-18',
    clockIn: '09:35',
    clockOut: '18:00',
    status: 'Late',
    notes: 'Heavy subway delay.',
  },
  // May 19
  {
    id: 'att-5',
    employeeId: 'emp-101',
    employeeName: 'Sarah Connor',
    date: '2026-05-19',
    clockIn: '08:58',
    clockOut: '17:45',
    status: 'Present',
  },
  {
    id: 'att-6',
    employeeId: 'emp-102',
    employeeName: 'James Carter',
    date: '2026-05-19',
    clockIn: '09:15',
    clockOut: '17:05',
    status: 'Late',
    notes: 'Traffic on 101 highway.',
  },
  {
    id: 'att-7',
    employeeId: 'emp-103',
    employeeName: 'Elena Rostova',
    date: '2026-05-19',
    clockIn: '08:50',
    clockOut: '17:00',
    status: 'Present',
  },
  {
    id: 'att-8',
    employeeId: 'emp-105',
    employeeName: 'David Kim',
    date: '2026-05-19',
    clockIn: '09:00',
    clockOut: '17:30',
    status: 'Present',
  },
  // May 20
  {
    id: 'att-9',
    employeeId: 'emp-101',
    employeeName: 'Sarah Connor',
    date: '2026-05-20',
    clockIn: '08:45',
    clockOut: '18:05',
    status: 'Present',
  },
  {
    id: 'att-10',
    employeeId: 'emp-103',
    employeeName: 'Elena Rostova',
    date: '2026-05-20',
    clockIn: '13:00', // Half Day
    clockOut: '17:45',
    status: 'Half Day',
    notes: 'Dentist appointment in the morning.',
  },
  {
    id: 'att-11',
    employeeId: 'emp-105',
    employeeName: 'David Kim',
    date: '2026-05-20',
    clockIn: '09:02',
    clockOut: '17:15',
    status: 'Present',
  },
  {
    id: 'att-12',
    employeeId: 'emp-106',
    employeeName: 'Sophia Patel',
    date: '2026-05-20',
    clockIn: '08:55',
    clockOut: '17:10',
    status: 'Present',
  }
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lve-201',
    employeeId: 'emp-104',
    employeeName: 'Marcus Vance',
    leaveType: 'Annual Leave',
    startDate: '2026-05-15',
    endDate: '2026-05-25',
    reason: 'Family trip outside of the region.',
    status: 'Approved',
    appliedDate: '2026-05-01'
  },
  {
    id: 'lve-202',
    employeeId: 'emp-101',
    employeeName: 'Sarah Connor',
    leaveType: 'Sick Leave',
    startDate: '2026-05-22',
    endDate: '2026-05-23',
    reason: 'Dental wisdom tooth extraction healing.',
    status: 'Pending',
    appliedDate: '2026-05-20'
  },
  {
    id: 'lve-203',
    employeeId: 'emp-103',
    employeeName: 'Elena Rostova',
    leaveType: 'Annual Leave',
    startDate: '2026-06-10',
    endDate: '2026-06-15',
    reason: 'Summer vacation renewal.',
    status: 'Approved',
    appliedDate: '2026-05-18'
  },
  {
    id: 'lve-204',
    employeeId: 'emp-105',
    employeeName: 'David Kim',
    leaveType: 'Compassionate',
    startDate: '2026-05-02',
    endDate: '2026-05-04',
    reason: 'Family emergency support.',
    status: 'Approved',
    appliedDate: '2026-04-30'
  },
  {
    id: 'lve-205',
    employeeId: 'emp-102',
    employeeName: 'James Carter',
    leaveType: 'Unpaid',
    startDate: '2026-07-01',
    endDate: '2026-07-05',
    reason: 'Attending brief external tech symposium.',
    status: 'Rejected',
    appliedDate: '2026-05-10'
  }
];

export const INITIAL_REIMBURSEMENTS: ReimbursementClaim[] = [
  {
    id: 'clm-301',
    employeeId: 'emp-101',
    employeeName: 'Sarah Connor',
    claimType: 'Dental Care',
    amount: 180,
    claimDate: '2026-05-15',
    description: 'Root canal treatment checkup invoice and follow-up.',
    receiptNumber: 'REC-9912A',
    status: 'Approved'
  },
  {
    id: 'clm-302',
    employeeId: 'emp-106',
    employeeName: 'Sophia Patel',
    claimType: 'Prescription',
    amount: 45,
    claimDate: '2026-05-19',
    description: 'Antibiotics & anti-inflammation prescription from City Meds.',
    receiptNumber: 'REC-2041B',
    status: 'Pending'
  },
  {
    id: 'clm-303',
    employeeId: 'emp-103',
    employeeName: 'Elena Rostova',
    claimType: 'Vision Care',
    amount: 320,
    claimDate: '2026-05-10',
    description: 'Prescription reading glasses frame & lens reimbursement.',
    receiptNumber: 'REC-1152X',
    status: 'Approved'
  },
  {
    id: 'clm-304',
    employeeId: 'emp-105',
    employeeName: 'David Kim',
    claimType: 'Medical Checkup',
    amount: 90,
    claimDate: '2026-05-01',
    description: 'Private specialist consult clinic - non-standard provider.',
    receiptNumber: 'REC-0812F',
    status: 'Rejected'
  }
];

export const INITIAL_PAYROLL: PayrollSlip[] = [
  {
    id: 'pay-401',
    employeeId: 'emp-101',
    employeeName: 'Sarah Connor',
    department: 'Engineering',
    role: 'Senior Software Architect',
    payPeriod: 'May 2026',
    baseSalary: 8500,
    bonus: 1200,
    allowance: 400,
    deductions: 250,
    netSalary: 9850,
    status: 'Paid',
    paymentDate: '2026-05-15'
  },
  {
    id: 'pay-402',
    employeeId: 'emp-102',
    employeeName: 'James Carter',
    department: 'Design',
    role: 'Product Designer',
    payPeriod: 'May 2026',
    baseSalary: 6200,
    bonus: 500,
    allowance: 300,
    deductions: 180,
    netSalary: 6820,
    status: 'Paid',
    paymentDate: '2026-05-15'
  },
  {
    id: 'pay-403',
    employeeId: 'emp-103',
    employeeName: 'Elena Rostova',
    department: 'HR',
    role: 'HR Director',
    payPeriod: 'May 2026',
    baseSalary: 7500,
    bonus: 800,
    allowance: 350,
    deductions: 220,
    netSalary: 8430,
    status: 'Paid',
    paymentDate: '2026-05-15'
  },
  {
    id: 'pay-404',
    employeeId: 'emp-105',
    employeeName: 'David Kim',
    department: 'Engineering',
    role: 'Junior Engineer',
    payPeriod: 'May 2026',
    baseSalary: 4500,
    bonus: 0,
    allowance: 250,
    deductions: 100,
    netSalary: 4650,
    status: 'Pending'
  },
  {
    id: 'pay-405',
    employeeId: 'emp-106',
    department: 'Sales',
    role: 'Account Executive',
    employeeName: 'Sophia Patel',
    payPeriod: 'May 2026',
    baseSalary: 5800,
    bonus: 1500,
    allowance: 300,
    deductions: 150,
    netSalary: 7450,
    status: 'Pending'
  }
];

